### PR TITLE
Games fix

### PR DESCRIPTION
**Pull request by twagger**
### Various fixes and little features for game : 

**Fixes**
- **fix**: user score is now correct when game ends
- **fix**: paddle collision is not bouncing anymore and is cleaner
- **fix**: players only have one pause per game now
- **fix**: update username or picture now impact player name or player picture
- **fix**: secured a check that was missing on 2fa authentification
- **fix**: images are now the same size in map modal
- **fix**: continue game after a server reboot is now working again, assuming that both players can reconnect
- **fix**: player status and matchmaking status is now correct after a server reboot
- **fix**: cancel a game now returns instantly to the lobby
- **fix**: viewers are now redirected to lobby when spectated a canceled game
- **fix**: securing game actions against spectator actions
- **fix**: modal now hides when click outside of it
- **fix**: securing unhandled throws
- **fix**: game now is ok when rejoining (no double player)
- **fix**: user now cannot go out of its game and rejoin or spectate another game
- **fix**: player now cannot leave the game navigating on an another page and come back to lobby with a wrong status
- **fix**: viewer is now removed from its game before joining another one throught matchmaking

**Features**
- **feat**: player names are now displayed in game
- **feat**: original map now is with retro font

### CODE REVIEW

**Review by fmonbeig — APPROVED** [review]
Good for me

**Review by Mastodoonte — APPROVED** [review]
All good

**Review by fmonbeig — APPROVED** [review]
Good for me

**Review by lefoun — APPROVED** [review]
lgtm

**Pull request merged**
