### PR TITLE
Merging Auth tom safe wtith main branch

### PR DESCRIPTION
**Pull request by lefoun**
Merging so that everyone can benefit from the infrastructure we built and start on the same page.

### CODE REVIEW

**Review by Mastodoonte — CHANGES_REQUESTED** [review]
node_modules in the pull request

**Comment by twagger** [comment]
node_modules have been removed in the last commits, it is ok for me.
We need to discuss about the global schema in conf folder on the server but nothing invalidating.

**Review by twagger — APPROVED** [review]
Ok for me

**Review by jnougaro — APPROVED** [review]
Review done, clean code.
I'm just not able to really judge it as I am not familiar with all the concepts.
There is just a comment in this file that maybe needs to be removed or updated srcs/server/src/auth/strategies/ft.strategy.ts

**Review by fmonbeig — APPROVED** [review]
I can not judge everything with my actual knowledge but I understand the structure of the project.

**Review by Mastodoonte — APPROVED** [review]
Merge with master approved. The code is clean but a bit unfamiliar for me so far.

**Pull request merged**
